// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi3Qm_muUBuzPAnERtvhYiHBg-dLjz2b0',
    appId: '1:88420486470:web:ac98a3ab9aa215b049e947',
    messagingSenderId: '88420486470',
    projectId: 'shoppingapp-b6f73',
    authDomain: 'shoppingapp-b6f73.firebaseapp.com',
    storageBucket: 'shoppingapp-b6f73.firebasestorage.app',
    measurementId: 'G-183GM04K0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-iluxoIozHuLKab0X7dsq2daY7sdyqh4',
    appId: '1:88420486470:android:a23bdf8f352600d049e947',
    messagingSenderId: '88420486470',
    projectId: 'shoppingapp-b6f73',
    storageBucket: 'shoppingapp-b6f73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHHNNz4kinPshZiIiolfpRgQtlfYSGcoY',
    appId: '1:88420486470:ios:51aa389179d941ec49e947',
    messagingSenderId: '88420486470',
    projectId: 'shoppingapp-b6f73',
    storageBucket: 'shoppingapp-b6f73.firebasestorage.app',
    iosBundleId: 'com.example.shoppingFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHHNNz4kinPshZiIiolfpRgQtlfYSGcoY',
    appId: '1:88420486470:ios:51aa389179d941ec49e947',
    messagingSenderId: '88420486470',
    projectId: 'shoppingapp-b6f73',
    storageBucket: 'shoppingapp-b6f73.firebasestorage.app',
    iosBundleId: 'com.example.shoppingFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi3Qm_muUBuzPAnERtvhYiHBg-dLjz2b0',
    appId: '1:88420486470:web:3daf25f1c66533a649e947',
    messagingSenderId: '88420486470',
    projectId: 'shoppingapp-b6f73',
    authDomain: 'shoppingapp-b6f73.firebaseapp.com',
    storageBucket: 'shoppingapp-b6f73.firebasestorage.app',
    measurementId: 'G-DMD7877HNF',
  );
}
